# Install and configure the sushy emulator locally. The emulator will be listening on the OOB network only.
# The sushy emulator will be backed against a local libvirt instance.
# NB: We will assume everything will be executed against the root user on the host. Since these are lab environments it
# should not cause a problem in doing everything as root!
- name: Configure environment for MetalFish
  hosts: localhost
  become: true
  roles:
    - docker
    - libvirt
  tasks:
    - name: Create Sushy directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/sushy"
        state: directory
        mode: "0755"

    - name: Copy sushy configuration to the sushy directory
      ansible.builtin.copy:
        src: "files/{{ item }}"
        dest: "{{ ansible_env.HOME }}/sushy"
        mode: "0644"
      loop: ["sushy-emulator.conf", "compose.yml"]

    - name: Execute docker compose
      ansible.builtin.command: docker compose up -d
      args:
        chdir: "{{ ansible_env.HOME }}/sushy"

- name: Define MetalFish servers
  hosts: metalfish
  gather_facts: false
  tasks:
    - name: Define vm from xml and set autostart
      delegate_to: localhost
      community.libvirt.virt:
        command: define
        xml: "{{ lookup('template', 'files/domain/vbmc-node.xml.j2') }}"
