---
- name: Clean local environment of Metal3
  hosts: localhost
  connection: local
  gather_facts: false
  pre_tasks:
    - name: Load virsh environment
      ansible.builtin.include_tasks: "{{ item }}"
      loop: ["tasks/list_networks.yml", "tasks/list_virtual_machines.yml"]
  tasks:
    - name: Debug virtual machines
      ansible.builtin.debug:
        var: current_virtual_machines

    - name: Remove virsh network
      community.libvirt.virt_net:
        name: "{{ network_name }}"
        command: "{{ item }}"
      loop: ["destroy", "undefine"]
      when: network_name in current_networks.list_nets

    - name: Clean up Virtual Machine
      when: vm_name in current_virtual_machines.list_vms
      block:
        - name: Get Virtual Machine Status
          community.libvirt.virt:
            name: "{{ vm_name }}"
            command: status
          register: current_status

        - name: Stop the Virtual Machine
          community.libvirt.virt:
            name: "{{ vm_name }}"
            command: destroy
          when: current_status.status != "shutdown"

        - name: Undefine the Virtual Machine
          community.libvirt.virt:
            name: "{{ vm_name }}"
            command: undefine
