---
- name: Configure local environment for Metal3
  hosts: all
  connection: local
  gather_facts: false
  tasks:
    - name: List Networks
      ansible.builtin.include_tasks:
        tasks/list_networks.yml

    - name: Debug networks
      ansible.builtin.debug:
        var: current_networks

    - name: Create a new network
      when: network_name not in current_networks.list_nets
      block:
        - name: Define a new network
          community.libvirt.virt_net:
            command: define
            name: "{{ network_name }}"
            xml: '{{ lookup("template", "files/network/bridge.xml.j2") }}'

        - name: Start a network
          community.libvirt.virt_net:
            command: create
            name: "{{ network_name }}"

    - name: Define vm from xml and set autostart
      community.libvirt.virt:
        command: define
        xml: "{{ lookup('template', 'files/domain/vbmc-node.xml.j2') }}"
