---
- name: Configure local environment for Metal3
  hosts: all
  connection: local
  gather_facts: false
  pre_tasks:
    - name: Load virsh environment
      ansible.builtin.include_tasks: "{{ item }}"
      loop: ["tasks/list_networks.yml", "tasks/list_virtual_machines.yml"]
  tasks:
    - name: Create a new network
      when: network_name not in current_networks.list_nets
      community.libvirt.virt_net:
        name: "{{ network_name }}"
        command: define
        xml: '{{ lookup("template", "files/network/bridge.xml.j2") }}'
      loop: ["define", "create"]

    - name: Define vm from xml and set autostart
      community.libvirt.virt:
        command: define
        xml: "{{ lookup('template', 'files/domain/vbmc-node.xml.j2') }}"
